start_message = 'I\'m a bot, I can check securitie\'s price and tell you when the security will cost as much as you need)0))'
request_to_add_message = 'Talk to me your securities. Please use this format (Name - Wanted price):\nName1 - 54\nName2 - 17'
request_to_del_message = 'Talk to me your securities to remove. Please use this format (Name):\nName1\nName2'
cancel_message = 'I hope we can talk again some day.'
gg_message = 'Mission complete'